language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DgW3De5UBrN+AEeVYzPev4j5gPuyKNc5dLL80SiPAFO6qWZkjXJIK8WfbeAbGkIqME97HiBXBha4UlRNcNELmLuIo/n0v27SF+l+xA39c0+iG49PNZMwdI9Z5Y6pNXVFFT6dyO8Y/JoYj4zxOmzXvGgiVakFzgcQVRiS7hRqqt4BaRyXC4f0LyKT3/QnwWwRt5IFicw1p6+LTkfbWKm9FYRiVOh8XsShW+G1C5WU39VeRTXHsWtOTMHwTgbyAV0hcecgHwxu51be8eR/JOl+75hILa230MevR3+tOkmBPu8xVdvV5610IuG4lIeYS2ScEMx216qCEJcMCkZcFMG6cCzKKYiZ9+VTEy3HDWa8o5rMElJP5fn9kODevGmpAsK1dkyYZW635Lh1gTDvl+fDVo19emZ7PZ8hErGmrYP70e3U7xJCiyG0jl9gFvNIdkgyT0I7+EmVs2oxWFtoyEvl+I9FFfDPdgSKGsZEyy+VcTOTMzD258bWyNwDijHyXLUfe74wgKoclMTPteA7huI3RGBgoROuf5sl+mJjHtZ6DHy9ImTy/M/IQvRJtRCV8rRjZFmqlBZEin3F3xlPSMULdRb7ohfW46RQB+MMVusKNHd8QEsmLChUihSnDYyrUUWk8TgK4I2A8MGcVI3/Z0fAGx2yV/F0KNMa3Ms1MWyHpOM=
  app: sleepy-atoll-78736
  on:
    repo: oscaralexander2125/blog-app-mongoose-challenge-solution
