language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: VuT7OxYP8ECZs74NvyGTVMJ1tfJrTxT4okrDeVUuksMXqxbjla0z5hPTLlmMg2z1wRnNECK8J1ezNb0cQ6vdpNXzmvjZP1XWvmshx8zwU9ca0k6cjl0epWippVwGqID6UKod7poI2cByy7qppHB1By6sSPV3ZMKBxS4/rmPkq08TvsUJ46SfCxiGUWEqBnOVIlGkq0z0SOMf4PKWz8PK38u/qY3c10WTX9VwHplwzbY4R3TGpyBARDETkZEE1TMVVL8umxHEfkWFdn6F9OcRVtSBcuTMjkVrH6x3gQJpH+LS7l+U1HZZMqJ7VpfoTZnyP+49xTh1VjoHkNd9C+SwI1HPBvuEdwFgde3ZwcwPqm6DQfn6zjT4scNO+PTW/9J8VMYmYyn+eWp++sMO89AyaNek8i9BjX3jBxN+kI8Y72k2Xzhd1b02yCQx1PCGQRToB5U55g4FfKYpnwBMff+0onB681oXH1mZKed556fl0wU9dQ01McuF/vVPjNWNE0Ony5LMKvZ+QUOnLRBUdebHH/IPN/ifw9MIbsIddHOnf5ozziYcW4uFam7W+V9srgky8NPDIvG+SDpzxx6ftmhGTO9MmyK3I4JGVsT3ih+oCTsf0ftMrC6B3Iu+h4HYg1KLCkOUv3f5dI26OfYKWu3L4HLn5FSCCtYwhcU7ZAHt1VY=
  app: sleepy-atoll-78736
  on:
    repo: oscaralexander2125/blog-app-mongoose-challenge-solution
